"""added updated_at

Revision ID: a6755d5bde97
Revises: cd5d5509991e
Create Date: 2021-07-20 19:57:33.882512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6755d5bde97'
down_revision = 'cd5d5509991e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    # ### end Alembic commands ###
